.TH "WEBASSETS" "1" "October 2012" "webassets"
.SH NAME
webassets \- Asset management for Python
.SH DESCRIPTION
Asset management application for Python web development \- use it to
merge and compress your JavaScript and CSS files.
.SS "positional arguments:"
.IP
{rebuild,watch,build,clean,check}
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-v\fR
be verbose
.TP
\fB\-q\fR
be quiet
.TP
\fB\-m\fR MODULE, \fB\-\-module\fR MODULE
read environment from a Python module
.IP
.SH AUTHOR
.sp
Michael Elsdörfer <\fI\%http://elsdoerfer.name\fP>
.sp
This manual page was initially written by Agustin Henze
<\fI\%tin@sluc.org.ar\fP>, for the Debian project.
.SH COPYRIGHT
2008, Michael Elsdörfer
